blog/urls.py
from django.urls import path, include

from .views import (
    Home,
    CategoryPost,
    PostPageView,
    ContactFormView,
    EmailSubscription,
    AboutView,
    PrivacyPolicyView,
    TermsOfServiceView,
    Search,
)
from blog.models import Post, Categorie, Comment
from write_blog.views import EditOrPublishDraft, EditOrSwitchPostToDraft

from compression_middleware.decorators import compress_page

app_name = 'blog'

urlpatterns = [
    path('', compress_page(Home.as_view()), name='home'),
    path('search', compress_page(Search.as_view()), name='search'),
    path('category/<slug:slug>',
         compress_page(CategoryPost.as_view()), name='category'),
    path('post/<str:id>/<slug:slug>/edit-post',
         compress_page(EditOrSwitchPostToDraft.as_view()), name='edit-post'),
    path('draft/<str:id>/edit-draft',
         compress_page(EditOrPublishDraft.as_view()), name='edit-or-publish-draft'),
    path('report/', compress_page(ContactFormView.as_view()), name='report'),
    path('contact/', compress_page(ContactFormView.as_view()), name='contact'),
    path('subscribe/', compress_page(EmailSubscription.as_view()), name='subscribe'),
    path('about/', compress_page(AboutView.as_view()), name='about'),
    path('privacy-policy/', compress_page(PrivacyPolicyView.as_view()),
         name='privacy_policy'),
    path('terms-of-service/',
         compress_page(TermsOfServiceView.as_view()), name='terms'),
    path('<slug:slug>', compress_page(
        PostPageView.as_view()), name='post_detail'),
]

codestim/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from blog.views import AboutView, handler404, handler500
from write_blog.views import image_upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls')),
    path('profile/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('media/images/uploads/', csrf_exempt(image_upload)),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = handler404
handler500 = handler500

registration/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView

from .views import User_signup, User_login, User_logout
from .forms import ResetPasswordForm

from compression_middleware.decorators import compress_page

app_name = 'registration'

urlpatterns = [
    path('signup/', compress_page(User_signup.as_view()), name='sign_up'),
    path('login/', compress_page(User_login.as_view()), name='log_in'),
    path('logout/', compress_page(User_logout), name='log_out'),
    path('password-reset/', compress_page(auth_views.PasswordResetView.as_view(template_name='authentication/resetPasswordFlow.html', success_url=reverse_lazy('registration:password_reset_done'))),
         name='password_reset'),

    path('password-reset/sent/', compress_page(auth_views.PasswordResetDoneView.as_view(template_name='authentication/resetPasswordFlow.html')),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', compress_page(PasswordResetConfirmView.as_view(
        template_name='authentication/resetPasswordForm.html',
        success_url=reverse_lazy('registration:password_reset_complete'),
        form_class=ResetPasswordForm
    )), name='password_reset_confirm'),

    path('password-reset/success/', compress_page(auth_views.PasswordResetCompleteView.as_view(
         template_name='authentication/resetPasswordFlow.html'
         )), name='password_reset_complete')
]

user_profile/urls.py
from django.urls import path, include

from .views import (
    Dashboard,
    Posts,
    Drafts,
    Comments,
    EditProfile,
    ProfileInfo,
    Search
)

from compression_middleware.decorators import compress_page

app_name = 'dashboard'

urlpatterns = [
    path('<str:user>/<str:id>/',
         compress_page(ProfileInfo.as_view()), name='profileInfo'),
    path('<str:user>/<str:id>/posts',
         compress_page(Posts.as_view()), name='posts'),
    path('<str:user>/<str:id>/drafts',
         compress_page(Drafts.as_view()), name='drafts'),
    path('<str:user>/<str:id>/comments',
         compress_page(Comments.as_view()), name='comments'),
    path('<str:user>/<str:id>/edit-profile',
         compress_page(EditProfile.as_view()), name='editProfile'),
    path('<str:user>/<str:id>/search',
         compress_page(Search.as_view()), name='search'),
    path('<str:user>/<str:id>/', include('write_blog.urls'))
]

user_profile/models.py
from django.db import models

user_profile/forms.py
from django import forms
from registration.models import User


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'bio', 'languages']

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'your first name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'your last name'}),
            'bio': forms.Textarea(attrs={'placeholder': 'brief introduction about yourself', 'required': 'True'}),
            'languages': forms.TextInput(attrs={'placeholder': 'programing languages you are working with'})
        }

user_profile/views.py
import uuid
import re

from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.views import View
from django.views.generic.edit import UpdateView
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.core.paginator import Paginator

from registration.models import User
from blog.models import Post, Comment, Draft
from .forms import EditProfileForm
from write_blog.forms import postForm

# Create your views here.


class Dashboard(LoginRequiredMixin, View):
    template_name = 'user_profile/dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        logged_user = request.user
        if kwargs['user'] != logged_user.username or kwargs['id'] != str(logged_user.userId):
            return HttpResponseForbidden("You are not authenticated to access this page")

        return super(Dashboard, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        print(args)
        return render(request, self.template_name)


class Posts(Dashboard):
    template_name = 'user_profile/posts.html'

    def get(self, request, *args, **kwargs):
        posts = Post.objects.filter(authorId=kwargs['id'])

        return render(request, self.template_name, {'posts': posts, 'model': 'post'})

    def post(self, request, *args, **kwargs):
        '''
        Handle POST method to delete posts
        '''
        user = request.user
        _id = request.POST.get('id')

        if _id:
            post = get_object_or_404(Post, postId=_id)
            post.delete()

        return redirect(request.path)


class Drafts(Dashboard):
    template_name = 'user_profile/drafts.html'

    def get(self, request, *args, **kwargs):
        drafts = Draft.objects.filter(authorId=kwargs['id'])

        return render(request, self.template_name, {'drafts': drafts, 'model': 'draft'})

    def post(self, request, *args, **kwargs):
        '''
        Handle POST method to delete drafts
        '''
        _id = request.POST.get('id')
        if _id:
            post = get_object_or_404(Draft, postId=_id)
            post.delete()

        return redirect(request.path)


class Comments(Dashboard):
    template_name = 'user_profile/comments.html'

    def get(self, request, *args, **kwargs):
        comments = Comment.objects.all().filter(
            post__authorId=self.kwargs['id'])

        '''
        Delete or approve comment
        '''
        _id = request.GET.get('id')
        if _id:
            comment = get_object_or_404(Comment, commentId=_id)
            if request.GET.get('action') == 'delete':
                comment.delete()
                messages.info(request, 'comment deleted')

                return redirect(request.path)

            else:
                approve = comment.approveOrDisapprove()
                messages.info(
                    request, 'Comment Approved' if approve else 'Comment Disapprove', extra_tags='info')

                return redirect(request.path)

        return render(request, self.template_name, {'comments': comments, 'model': 'comment'})


class ProfileInfo(Dashboard):
    template_name = 'user_profile/profileInfo.html'

    def get(self, request, *args, **kwargs):
        profile = User.objects.get(userId=request.user.userId)

        return render(request, self.template_name, {'profile': profile})


class EditProfile(LoginRequiredMixin, UpdateView):
    form_class = EditProfileForm
    template_name = 'user_profile/editProfile.html'

    def dispatch(self, request, **kwargs):
        logged_user = request.user
        if logged_user.username != kwargs['user'] or str(logged_user.userId) != kwargs['id']:
            return HttpResponseForbidden('You are not authenticated to access this page')

        return super().dispatch(request, **kwargs)

    def get_object(self):
        user = self.request.user
        return User.objects.get(userId=user.userId)

    def form_valid(self, form):
        fname = form.cleaned_data['first_name']
        lname = form.cleaned_data['last_name']
        bio = form.cleaned_data['bio']

        user = form.save(commit=False)
        if fname and lname and bio:
            user.isAuthor = True
        else:
            user.isAuthor = False

        messages.success(
            self.request, 'Profile saved successfully', extra_tags='success')
        user.save()

        return super().form_valid(form)

    def get_success_url(self, **kwargs):
        user = self.request.user
        return reverse('dashboard:editProfile', kwargs={
            'user': user.username,
            'id': user.userId
        })


class Search(View):
    template_name = 'user_profile/searchResult.html'

    def get(self, request, *args, **kwargs):
        query = request.GET['query']
        result_found = False

        if len(query) > 60 or len(query) == 0:
            search_result = []
        else:
            model = request.GET.get('model')
            if model == 'post':
                results = Post.objects.filter(title__icontains=query)
            elif model == 'draft':
                results = Draft.objects.filter(title__icontains=query)
            else:
                results = Comment.objects.filter(comment__icontains=query)

        if results:
            post_per_page = Paginator(results, 10)
            page_number = self.request.GET.get('page')
            search_result = post_per_page.get_page(page_number)
            result_found = True

        else:
            search_result = []

        context_dict = {
            'results': search_result,
            'result_length': len(search_result),
            'query': query,
            'model': model,
            'result_found': result_found
        }

        return render(request, self.template_name, context_dict)

    def post(self, request, *args, **kwargs):
        redirect_path = request.POST.get('next')
        _id = request.POST.get('id')
        model = request.POST.get('model')

        if _id:
            if model == 'post':
                obj = Post.objects.get(postId=_id)
                obj.delete()

            if model == 'draft':
                obj = Draft.objects.get(postId=_id)
                obj.delete()

            if model == 'comment':
                action = request.POST.get('action')
                comment = Comment.objects.get(commentId=_id)

                if action == 'delete':
                    comment.delete()
                    messages.info(request, 'comment deleted')
                else:
                    approve = comment.approveOrDisapprove()
                    messages.info(
                        request, 'comment approved' if approve else 'comment Disapprove')

        return redirect(redirect_path)

templates/user_profile/dashboard.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@500&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <script defer type="module" src="{% static 'js/dashboard.js' %}"></script>
    <script defer src="{% static 'js/toggleSidebar.js' %}"></script>
    <style>
        #main {
            width: 100%;
            height: 100%;
            position: relative;
        }
    </style>
</head>

{% block dashboard_right_block_head %}
{% endblock %}

<body>
    <header id="header">
        <nav class='nav-bar flex flex-row center-align container'>
            <svg id="burger" style="display: none;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                <path
                    d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" />
            </svg>
            <svg id="cross" style="display: none;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512">
                <path
                    d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z" />
            </svg>
            <div class="nav-bar__auth">
                <div class="auth flex flex-row center-align">
                    <div class="auth__profile flex flex-row center-align">
                        <a href="{% url 'dashboard:profileInfo' user=user id=user.userId %}">
                            <svg class="auth__profile--icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                                <path
                                    d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z" />
                            </svg>
                        </a>
                        <a class='auth__profile--username link'
                            href="{% url 'dashboard:profileInfo' user=user id=user.userId %}">{{user}}</a>
                    </div><a class="auth__btn link btn" href="{% url 'registration:log_out' %}">Logout</a>
                </div>
            </div>
        </nav>
    </header>
    <main id="main">
        <div class="dashboard flex">
            <div class="dashboard__sidebar flex flex-column">
                <ul class="dashboard__sidebar__navitems">
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:profileInfo' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                <path
                                    d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z" />
                            </svg>
                            <p class="link-name">Profile</p>
                        </a>
                    </li>
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:posts' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                <path
                                    d="M172.2 226.8c-14.6-2.9-28.2 8.9-28.2 23.8V301c0 10.2 7.1 18.4 16.7 22 18.2 6.8 31.3 24.4 31.3 45 0 26.5-21.5 48-48 48s-48-21.5-48-48V120c0-13.3-10.7-24-24-24H24c-13.3 0-24 10.7-24 24v248c0 89.5 82.1 160.2 175 140.7 54.4-11.4 98.3-55.4 109.7-109.7 17.4-82.9-37-157.2-112.5-172.2zM209 0c-9.2-.5-17 6.8-17 16v31.6c0 8.5 6.6 15.5 15 15.9 129.4 7 233.4 112 240.9 241.5.5 8.4 7.5 15 15.9 15h32.1c9.2 0 16.5-7.8 16-17C503.4 139.8 372.2 8.6 209 0zm.3 96c-9.3-.7-17.3 6.7-17.3 16.1v32.1c0 8.4 6.5 15.3 14.8 15.9 76.8 6.3 138 68.2 144.9 145.2.8 8.3 7.6 14.7 15.9 14.7h32.2c9.3 0 16.8-8 16.1-17.3-8.4-110.1-96.5-198.2-206.6-206.7z" />
                            </svg>
                            <p class="link-name">Posts</p>
                        </a>
                    </li>
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:drafts' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                <path
                                    d="M457.01 344.42c-25.05 20.33-52.63 37.18-82.54 49.05l54.38 94.19 53.95 23.04c9.81 4.19 20.89-2.21 22.17-12.8l7.02-58.25-54.98-95.23zm42.49-94.56c4.86-7.67 1.89-17.99-6.05-22.39l-28.07-15.57c-7.48-4.15-16.61-1.46-21.26 5.72C403.01 281.15 332.25 320 256 320c-23.93 0-47.23-4.25-69.41-11.53l67.36-116.68c.7.02 1.34.21 2.04.21s1.35-.19 2.04-.21l51.09 88.5c31.23-8.96 59.56-25.75 82.61-48.92l-51.79-89.71C347.39 128.03 352 112.63 352 96c0-53.02-42.98-96-96-96s-96 42.98-96 96c0 16.63 4.61 32.03 12.05 45.66l-68.3 118.31c-12.55-11.61-23.96-24.59-33.68-39-4.79-7.1-13.97-9.62-21.38-5.33l-27.75 16.07c-7.85 4.54-10.63 14.9-5.64 22.47 15.57 23.64 34.69 44.21 55.98 62.02L0 439.66l7.02 58.25c1.28 10.59 12.36 16.99 22.17 12.8l53.95-23.04 70.8-122.63C186.13 377.28 220.62 384 256 384c99.05 0 190.88-51.01 243.5-134.14zM256 64c17.67 0 32 14.33 32 32s-14.33 32-32 32-32-14.33-32-32 14.33-32 32-32z" />
                            </svg>
                            <p class="link-name">Draft</p>
                        </a>
                    </li>
                    <div class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:comments' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">
                                <path
                                    d="M416 192c0-88.4-93.1-160-208-160S0 103.6 0 192c0 34.3 14.1 65.9 38 92-13.4 30.2-35.5 54.2-35.8 54.5-2.2 2.3-2.8 5.7-1.5 8.7S4.8 352 8 352c36.6 0 66.9-12.3 88.7-25 32.2 15.7 70.3 25 111.3 25 114.9 0 208-71.6 208-160zm122 220c23.9-26 38-57.7 38-92 0-66.9-53.5-124.2-129.3-148.1.9 6.6 1.3 13.3 1.3 20.1 0 105.9-107.7 192-240 192-10.8 0-21.3-.8-31.7-1.9C207.8 439.6 281.8 480 368 480c41 0 79.1-9.2 111.3-25 21.8 12.7 52.1 25 88.7 25 3.2 0 6.1-1.9 7.3-4.8 1.3-2.9.7-6.3-1.5-8.7-.3-.3-22.4-24.2-35.8-54.5z" />
                            </svg>
                            <p class="link-name">Comments</p>
                        </a>
                    </div>
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:write_blog:write_post' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                <path
                                    d="M400 480H48c-26.5 0-48-21.5-48-48V80c0-26.5 21.5-48 48-48h352c26.5 0 48 21.5 48 48v352c0 26.5-21.5 48-48 48zM238.1 177.9L102.4 313.6l-6.3 57.1c-.8 7.6 5.6 14.1 13.3 13.3l57.1-6.3L302.2 242c2.3-2.3 2.3-6.1 0-8.5L246.7 178c-2.5-2.4-6.3-2.4-8.6-.1zM345 165.1L314.9 135c-9.4-9.4-24.6-9.4-33.9 0l-23.1 23.1c-2.3 2.3-2.3 6.1 0 8.5l55.5 55.5c2.3 2.3 6.1 2.3 8.5 0L345 199c9.3-9.3 9.3-24.5 0-33.9z" />
                            </svg>
                            <p class="link-name">Write Post</p>
                        </a>
                    </li>
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link"
                            href="{% url 'dashboard:editProfile' user=user.username id=user.userId %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512">
                                <path
                                    d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h274.9c-2.4-6.8-3.4-14-2.6-21.3l6.8-60.9 1.2-11.1 7.9-7.9 77.3-77.3c-24.5-27.7-60-45.5-99.9-45.5zm45.3 145.3l-6.8 61c-1.1 10.2 7.5 18.8 17.6 17.6l60.9-6.8 137.9-137.9-71.7-71.7-137.9 137.8zM633 268.9L595.1 231c-9.3-9.3-24.5-9.3-33.8 0l-37.8 37.8-4.1 4.1 71.8 71.7 41.8-41.8c9.3-9.4 9.3-24.5 0-33.9z" />
                            </svg>
                            <p class="link-name">Edit Profile</p>
                        </a>
                    </li>
                    <li class="list dashboard__sidebar__navitems--link">
                        <a class="link dashboard-left-menu-link" href="{% url 'blog:home' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                                <path
                                    d="M326.612 185.391c59.747 59.809 58.927 155.698.36 214.59-.11.12-.24.25-.36.37l-67.2 67.2c-59.27 59.27-155.699 59.262-214.96 0-59.27-59.26-59.27-155.7 0-214.96l37.106-37.106c9.84-9.84 26.786-3.3 27.294 10.606.648 17.722 3.826 35.527 9.69 52.721 1.986 5.822.567 12.262-3.783 16.612l-13.087 13.087c-28.026 28.026-28.905 73.66-1.155 101.96 28.024 28.579 74.086 28.749 102.325.51l67.2-67.19c28.191-28.191 28.073-73.757 0-101.83-3.701-3.694-7.429-6.564-10.341-8.569a16.037 16.037 0 0 1-6.947-12.606c-.396-10.567 3.348-21.456 11.698-29.806l21.054-21.055c5.521-5.521 14.182-6.199 20.584-1.731a152.482 152.482 0 0 1 20.522 17.197zM467.547 44.449c-59.261-59.262-155.69-59.27-214.96 0l-67.2 67.2c-.12.12-.25.25-.36.37-58.566 58.892-59.387 154.781.36 214.59a152.454 152.454 0 0 0 20.521 17.196c6.402 4.468 15.064 3.789 20.584-1.731l21.054-21.055c8.35-8.35 12.094-19.239 11.698-29.806a16.037 16.037 0 0 0-6.947-12.606c-2.912-2.005-6.64-4.875-10.341-8.569-28.073-28.073-28.191-73.639 0-101.83l67.2-67.19c28.239-28.239 74.3-28.069 102.325.51 27.75 28.3 26.872 73.934-1.155 101.96l-13.087 13.087c-4.35 4.35-5.769 10.79-3.783 16.612 5.864 17.194 9.042 34.999 9.69 52.721.509 13.906 17.454 20.446 27.294 10.606l37.106-37.106c59.271-59.259 59.271-155.699.001-214.959z" />
                            </svg>
                            <p class="link-name">Home</p>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="dashboard__content">
                <div class="dashboard__content--body">
                    {% block alert_block %}
                    {% endblock %}

                    {% if '/posts' in request.path or '/drafts' in request.path or '/comments' in request.path or '/search' in request.path%}
                    {% include 'user_profile/dashboardSearchbar.html' with user=user model=model %}
                    {% endif %}

                    {% block dashboard_right_block %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </main>
</body>

</html>

templates/user_profile/dashboardSearchbar.html
<form action="{% url 'dashboard:search' user=user id=user.userId %}" class="search-bar flex flex-row" method="GET">
    <input type="search" name="model" value='{{model}}' hidden>
    <input class="search-bar--input" required type="search" name="query" placeholder="Search anything here..."
        id="search">
    <button class="search-bar__btn" aria-label="search" type="submit">Search
    </button>
</form>

templates/user_profile/drafts.html
{% extends 'user_profile/dashboard.html' %}
{% load static %}

{% block dashboard_right_block_head %}
<title>Draft</title>
<script type="module" defer src="{% static 'js/modal.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/itemList.css' %}">
<link rel="stylesheet" href="{% static 'css/modal.css' %}">
{% endblock %}

{% block alert_block %}
{% include 'message.html' with message=message %}
{% endblock %}

{% block dashboard_right_block %}
<h1 class="page-title">Drafts</h1>
{% if drafts %}
{% for draft in drafts %}
<div class="card">
    <div class="card__text">
        <h3 class="card__text--title">{{draft.title}}</h3>
        <p class="card__text--meta">Category: <span>{{draft.category}}</span> </p>
        <p class="card__text--meta">Tags:
            {% if draft.tags %}
            <span>{{draft.tags}}</span>
            {% else %}
            <span></span>
            {% endif %}
        </p>

    </div>
    <div class="card__btn">
        <a class="link card__btn--edit" href="{% url 'blog:edit-or-publish-draft' id=draft.postId %}">Edit</a>
        <button class="card__btn--delete delete" type="text" name="delete" data-extra="{{draft.title}}"
            value="{{draft.postId}}">Delete</button>
    </div>
</div>
{% endfor %}
<div class="modal-container" id="modal-container">
    {% include 'modalForm.html' with type="draft" %}
</div>
{% else %}
<div class="no-content">
    <div class="wrapper">
        <p class="info">No Drafts</p>
    </div>
</div>
{% endif %}
{% endblock %}