blog/urls.py
from django.urls import path, include

from .views import (
    Home,
    CategoryPost,
    PostPageView,
    ContactFormView,
    EmailSubscription,
    AboutView,
    PrivacyPolicyView,
    TermsOfServiceView,
    Search,
)
from blog.models import Post, Categorie, Comment
from write_blog.views import EditOrPublishDraft, EditOrSwitchPostToDraft

from compression_middleware.decorators import compress_page

app_name = 'blog'

urlpatterns = [
    path('', compress_page(Home.as_view()), name='home'),
    path('search', compress_page(Search.as_view()), name='search'),
    path('category/<slug:slug>',
         compress_page(CategoryPost.as_view()), name='category'),
    path('post/<str:id>/<slug:slug>/edit-post',
         compress_page(EditOrSwitchPostToDraft.as_view()), name='edit-post'),
    path('draft/<str:id>/edit-draft',
         compress_page(EditOrPublishDraft.as_view()), name='edit-or-publish-draft'),
    path('report/', compress_page(ContactFormView.as_view()), name='report'),
    path('contact/', compress_page(ContactFormView.as_view()), name='contact'),
    path('subscribe/', compress_page(EmailSubscription.as_view()), name='subscribe'),
    path('about/', compress_page(AboutView.as_view()), name='about'),
    path('privacy-policy/', compress_page(PrivacyPolicyView.as_view()),
         name='privacy_policy'),
    path('terms-of-service/',
         compress_page(TermsOfServiceView.as_view()), name='terms'),
    path('<slug:slug>', compress_page(
        PostPageView.as_view()), name='post_detail'),
]

codestim/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from blog.views import AboutView, handler404, handler500
from write_blog.views import image_upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls')),
    path('profile/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('media/images/uploads/', csrf_exempt(image_upload)),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = handler404
handler500 = handler500

registration/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView

from .views import User_signup, User_login, User_logout
from .forms import ResetPasswordForm

from compression_middleware.decorators import compress_page

app_name = 'registration'

urlpatterns = [
    path('signup/', compress_page(User_signup.as_view()), name='sign_up'),
    path('login/', compress_page(User_login.as_view()), name='log_in'),
    path('logout/', compress_page(User_logout), name='log_out'),
    path('password-reset/', compress_page(auth_views.PasswordResetView.as_view(template_name='authentication/resetPasswordFlow.html', success_url=reverse_lazy('registration:password_reset_done'))),
         name='password_reset'),

    path('password-reset/sent/', compress_page(auth_views.PasswordResetDoneView.as_view(template_name='authentication/resetPasswordFlow.html')),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', compress_page(PasswordResetConfirmView.as_view(
        template_name='authentication/resetPasswordForm.html',
        success_url=reverse_lazy('registration:password_reset_complete'),
        form_class=ResetPasswordForm
    )), name='password_reset_confirm'),

    path('password-reset/success/', compress_page(auth_views.PasswordResetCompleteView.as_view(
         template_name='authentication/resetPasswordFlow.html'
         )), name='password_reset_complete')
]

templates/authentication/login.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
{% load account %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}" />
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <script defer src="{% static 'js/auth.js' %}"></script>
</head>

<body>
    <div id="content">
        {% include 'message.html' with message=message %}
        <div class="wrapper">
            <h1 class="auth-form__name">Login</h1>
            <div class="auth-options">
                <div class="auth-options__btn flex wrap">
                    <a href="{% provider_login_url 'google' method='oauth2' %}" class="auth-options__btn--google flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512">
                            <path
                                d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z" />
                        </svg>
                    </a>
                    <a href="{% provider_login_url 'facebook' method='oauth2' %}"
                        class="auth-options__btn--facebook flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z" />
                        </svg>
                    </a>
                    <a href="{% provider_login_url 'github' %}" class="auth-options__btn--github flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                            <path
                                d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z" />
                        </svg>
                    </a>
                </div>
            </div>
            <div class="email-signup">
                <span class="email-signup--message">or use your email for login</span>
            </div>
            <form id="signup-form" class="auth-form" method="POST">
                {% csrf_token %}
                <div class="auth-form__input-items">
                    <div class="auth-form__input">
                        <div class="auth-form__input--fields">
                            {{form.email}}
                        </div>
                        <div class="errors">
                            {% if form.errors %}
                            {{form.errors.email}}
                            {% endif %}
                        </div>
                    </div>
                    <div class="auth-form__input">
                        <div class="auth-form__input--fields">
                            {{form.password}}
                        </div>
                        <div class="errors">
                            {% if form.errors %}
                            {{form.non_field_errors}}
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="auth-form__btn flex flex-column">
                    <p class="auth-form__btn--reset message-info"><a class="default-link"
                            href="{% url 'registration:password_reset' %}">Reset
                            Password</a></p>
                    {% if request.GET.next %}
                    <button class="auth-form__btn--submit btn" type="submit" name="next"
                        value="{{request.GET.next}}">LOGIN</button>
                    {% else %}
                    <button class="auth-form__btn--submit btn" type="submit" name="login">LOGIN</button>
                    {% endif %}
                    <p class="auth-form--message">Don't have an account?<a style="margin-left: .2rem;"
                            class="default-link" href="{% url 'registration:sign_up' %}">
                            Signup</a></p>
                    <a class="default-link" href="{% url 'blog:home' %}">Go back
                        to
                        website</a>
                </div>
            </form>
        </div>
    </div>
</body>

</html>

templates/authentication/resetPasswordFlow.html
<!DOCTYPE html>
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="preload" as="style" onload="this.rel='stylesheet'" href="{% static 'css/global.css' %}">
    <link rel="preload" as="style" onload="this.rel='stylesheet'" href="{% static 'css/auth.css' %}">
</head>

<body>
    <div id="content">
        {% include 'message.html' with message=message %}
        <div class="wrapper" style="max-width: 750px;">
            {% if request.path == '/user/password-reset/' %}
            <form id="signup-form" class="auth-form" method="POST" style="margin-bottom: 1rem;">
                <h1 class="auth-form__name">Reset Password</h1>

                <p style="font-size: 1rem; color: #41444b" class="message-info">Enter your registreted Email address. We
                    are
                    sent
                    you a
                    password reset link to that
                    email address.</p>
                {% csrf_token %}
                <div class="auth-form__input-items">
                    <div class="auth-form__input">
                        <label class="auth-form__input--label" for="{{form.email.id_for_label}}">
                            {{form.email.label}}
                        </label>
                        <div class="auth-form__input--fields">
                            <input type="email" name="email" autocomplete="email" required
                                id="{{form.email.id_for_label}}" placeholder="Enter Your Email">
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.email}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth-form__btn flex flex-column">
                    <button class="auth-form__btn--submit btn" type="submit" name="login">SEND</button>
                </div>
            </form>
            {% endif %}
            {% if request.path == '/user/password-reset/sent/' %}
            <div class="password-reset-card">
                <p style="font-size: .9rem; color: #41444b; margin: 0 0 1rem 0;" class="message-info">We’ve emailed you
                    instructions for
                    setting your
                    password,
                    if an
                    account exists with the
                    email you entered.
                    You should receive them shortly.

                    If you don’t receive an email, please make sure you’ve entered the address you registered with,
                    and
                    check
                    your spam folder.</p>
            </div>
            {% endif %}
            {% if request.path == '/user/password-reset/success/' %}
            <div>
                <p style="margin: 0 0 1rem 0;" class="message-success">Your password has been succesfully set. You
                    can
                    <a class="default-link" href="{% url 'registration:log_in' %}">Login</a> now.</p>
            </div>
            {% endif %}
            <a style="margin-top: 1rem;" class="default-link" href="{% url 'blog:home' %}">Go back
                to
                website</a>
        </div>
    </div>
</body>

</html>

templates/authentication/resetPasswordForm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset password</title>
    <link rel="stylesheet" href="{% static 'css/auth.css' %}" />
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Mukta:wght@500;600;700;800&family=Rubik:wght@400;500;700&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;500;600;700&display=swap" rel="stylesheet">
    <script defer src="{% static 'js/auth.js' %}"></script>
</head>

<body>
    <div id="content">
        <div class="wrapper" style="max-width: 35rem;">
            <h1 class="auth-form__name">New Password</h1>
            {% if validlink %}
            <form class="auth-form" method="POST" style="margin-bottom: 1rem;">
                {% csrf_token %}
                <div class="auth-form__input-items">
                    <div class="auth-form__input">
                        <div class="auth-form__input--fields">
                            <input type="password" name="new_password1" autocomplete="new-password"
                                placeholder="password" required="" id="id_new_password1">
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.new_password1}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="auth-form__input">
                        <div class="auth-form__input--fields">
                            <input type="password" name="new_password2" autocomplete="new-password"
                                placeholder="Confirm Password" required="" id="id_new_password2">
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.new_password2}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth-form__btn flex flex-column">
                    <button class="auth-form__btn--submit btn" type="submit" name="login">SAVE</button>
                </div>
            </form>
            {% else %}
            <p class="message-error" style="margin: 0 0 1rem 0;">The password reset link was invalid, possibly because
                it
                has already been used.
                Please
                request a new password reset link. <a class="default-link"
                    href="{% url 'registration:password_reset' %}">Reset password</a></p>
            {% endif %}
            <a style="margin-top: 1rem;" class="default-link" href="{% url 'blog:home' %}">Go back
                to
                website</a>
        </div>
    </div>
</body>

</html>

templates/authentication/signup.html
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
{% load account %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="preload" as="style" onload="this.rel='stylesheet'" href="{% static 'css/auth.css' %}" />
    <link rel="preload" as="style" onload="this.rel='stylesheet'" href="{% static 'css/global.css' %}" />
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>

<body>
    <div id="content">
        {% include 'message.html' with message=message %}
        <div class="wrapper">
            <h1 class="auth-form__name">Create Account</h1>
            <div class="auth-options">
                <div class="auth-options__btn flex wrap">
                    <a href="{% provider_login_url 'google' method='oauth2' %}" class="auth-options__btn--google flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 488 512">
                            <path
                                d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z" />
                        </svg>
                    </a>
                    <a href="{% provider_login_url 'facebook' method='oauth2' %}"
                        class="auth-options__btn--facebook flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path
                                d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z" />
                        </svg>
                    </a>
                    <a href="{% provider_login_url 'github' %}" class="auth-options__btn--github flex">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
                            <path
                                d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3.3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5.3-6.2 2.3zm44.2-1.7c-2.9.7-4.9 2.6-4.6 4.9.3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3.7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3.3 2.9 2.3 3.9 1.6 1 3.6.7 4.3-.7.7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3.7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3.7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z" />
                        </svg>
                    </a>
                </div>
            </div>
            <div class="email-signup">
                <span class="email-signup--message">or use your email for resigtration</span>
            </div>
            <form id="signup-form" class="auth-form" method="POST">
                {% csrf_token %}
                <div class="auth-form__input-items">
                    <div class="auth-form__input">
                        <label class="auth-form__input--label" for={{form.username.id_for_label}}>
                            {{form.username.label}}
                        </label>
                        <div class="auth-form__input--fields">
                            {{form.username}}
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.username}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="auth-form__input">
                        <label class="auth-form__input--label" for={{form.email.id_for_label}}>
                            {{form.email.label}}
                        </label>
                        <div class="auth-form__input--fields">
                            {{form.email}}
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.email}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="auth-form__input">
                        <label class="auth-form__input--label" for={{form.password1.id_for_label}}>
                            {{form.password1.label}}
                        </label>
                        <div class="auth-form__input--fields">
                            {{form.password1}}
                        </div>
                        <p class="auth-form--message">Password should be more than 8 character long.
                            Including lower, upper and special characters.</p>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.password1}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="auth-form__input">
                        <label class="auth-form__input--label" for={{form.password2.id_for_label}}>
                            {{form.password2.label}}
                        </label>
                        <div class="auth-form__input--fields">
                            {{form.password2}}
                        </div>
                        {% if form.errors %}
                        <div class="errors">
                            {{form.errors.password2}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="auth-form__input">
                        <div class="auth-form__input--fields g-recaptcha"
                            data-sitekey="6Lca6PAZAAAAAK1r9e_s5zDt6cf4JOe6GvgjOdbO">
                        </div>
                        {% if form.non_field_errors %}
                        <div class="errors">
                            {{form.non_field_errors}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="auth-form__btn flex-column flex">
                    <button class="auth-form__btn--submit btn" type="submit" name="sign_up">
                        SIGN UP
                    </button>
                    <p class="auth-form--message">Already have an account?<a style="margin-left: .2rem;"
                            class="default-link" href="{% url 'registration:log_in' %}">Login</a>
                    </p>
                    <a class="default-link" href="{% url 'blog:home' %}">Go back
                        to
                        website</a>
                </div>
            </form>
        </div>
    </div>
</body>

</html>