blog/urls.py
from django.urls import path, include

from .views import (
    Home,
    CategoryPost,
    PostPageView,
    ContactFormView,
    EmailSubscription,
    AboutView,
    PrivacyPolicyView,
    TermsOfServiceView,
    Search,
)
from blog.models import Post, Categorie, Comment
from write_blog.views import EditOrPublishDraft, EditOrSwitchPostToDraft

from compression_middleware.decorators import compress_page

app_name = 'blog'

urlpatterns = [
    path('', compress_page(Home.as_view()), name='home'),
    path('search', compress_page(Search.as_view()), name='search'),
    path('category/<slug:slug>',
         compress_page(CategoryPost.as_view()), name='category'),
    path('post/<str:id>/<slug:slug>/edit-post',
         compress_page(EditOrSwitchPostToDraft.as_view()), name='edit-post'),
    path('draft/<str:id>/edit-draft',
         compress_page(EditOrPublishDraft.as_view()), name='edit-or-publish-draft'),
    path('report/', compress_page(ContactFormView.as_view()), name='report'),
    path('contact/', compress_page(ContactFormView.as_view()), name='contact'),
    path('subscribe/', compress_page(EmailSubscription.as_view()), name='subscribe'),
    path('about/', compress_page(AboutView.as_view()), name='about'),
    path('privacy-policy/', compress_page(PrivacyPolicyView.as_view()),
         name='privacy_policy'),
    path('terms-of-service/',
         compress_page(TermsOfServiceView.as_view()), name='terms'),
    path('<slug:slug>', compress_page(
        PostPageView.as_view()), name='post_detail'),
]

codestim/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from blog.views import AboutView, handler404, handler500
from write_blog.views import image_upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls')),
    path('profile/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('media/images/uploads/', csrf_exempt(image_upload)),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = handler404
handler500 = handler500

user_profile/urls.py
from django.urls import path, include

from .views import (
    Dashboard,
    Posts,
    Drafts,
    Comments,
    EditProfile,
    ProfileInfo,
    Search
)

from compression_middleware.decorators import compress_page

app_name = 'dashboard'

urlpatterns = [
    path('<str:user>/<str:id>/',
         compress_page(ProfileInfo.as_view()), name='profileInfo'),
    path('<str:user>/<str:id>/posts',
         compress_page(Posts.as_view()), name='posts'),
    path('<str:user>/<str:id>/drafts',
         compress_page(Drafts.as_view()), name='drafts'),
    path('<str:user>/<str:id>/comments',
         compress_page(Comments.as_view()), name='comments'),
    path('<str:user>/<str:id>/edit-profile',
         compress_page(EditProfile.as_view()), name='editProfile'),
    path('<str:user>/<str:id>/search',
         compress_page(Search.as_view()), name='search'),
    path('<str:user>/<str:id>/', include('write_blog.urls'))
]

write_blog/urls.py
from django.urls import path

from .views import CreatePost

from compression_middleware.decorators import compress_page

app_name = 'write_blog'

urlpatterns = [
    path('write-post/', compress_page(CreatePost.as_view()), name='write_post')
]

write_blog/forms.py
from django import forms
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from blog.models import Categorie, Draft


def postForm(modelName):
    class WritePost(forms.ModelForm):
        category = forms.ModelChoiceField(
            queryset=Categorie.objects.all(), empty_label="Choose Category", to_field_name="name")

        class Meta:
            model = modelName
            fields = ['category', 'title',
                      'body', 'featured_image', 'tags', 'meta_title', 'slug', 'meta_description']

            widgets = {
                'title': forms.TextInput(attrs={
                    'placeholder': 'Enter title here',
                    'autocomplete': 'off',
                }),
                'tags': forms.TextInput(attrs={
                    'placeholder': 'Enter tags (separate by comma)',
                    'autocomplete': 'off',
                }),
                'meta_title': forms.TextInput(attrs={
                    'placeholder': 'Meta title',
                    'autocomplete': 'off'
                }),
                'slug': forms.TextInput(attrs={
                    'placeholder': 'Parmalink',
                    'autocomplete': 'off'
                }),
                'meta_description': forms.Textarea(attrs={
                    'placeholder': 'Meta description',
                    'autocomplete': 'off',
                    'rows': 10
                })
            }

    return WritePost

write_blog/views.py
import re
import unidecode
import os

from bs4 import BeautifulSoup
from PIL import Image

from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.decorators.csrf import csrf_exempt, requires_csrf_token
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseForbidden, JsonResponse, HttpResponse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.conf import settings
from django.core.files import File
from django.core.files.storage import FileSystemStorage

from registration.models import User
from blog.models import Tag, Post, Draft
from .forms import postForm


@requires_csrf_token
def image_upload(request):
    image_file = request.FILES['file']

    fs = FileSystemStorage(location=os.path.join(
        settings.MEDIA_ROOT, 'uploads'))
    image_save = fs.save(image_file.name, image_file)
    image_path = fs.path(image_save)

    image = Image.open(image_path)
    resize_image = image.resize((778, 519))
    resize_image.save(image_path, quality=50, optimize=True)

    image_location = settings.MEDIA_URL + 'uploads/' + image_file.name
    return JsonResponse({'location': image_location})


class CreatePost(LoginRequiredMixin, CreateView):
    '''
    This view is responsible for create a new post or
    save as draft.
    '''

    template_name = 'write_blog/writePost.html'

    def get_form_class(self):
        if 'save' in self.request.POST:
            return postForm(Draft)
        return postForm(Post)

    def get_context_data(self, *args, **kwargs):
        context = super(CreatePost, self).get_context_data()
        context['writePost'] = True

        return context

    def form_valid(self, form):
        postSavingFormHandle(self.request, form)
        return super(CreatePost, self).form_valid(form)

    def get_success_url(self):
        user = self.request.user
        return reverse(f"dashboard:{'drafts' if 'save' in self.request.POST else 'posts'}", kwargs={
            'user': user.username,
            'id': user.userId
        })


class EditOrSwitchPostToDraft(LoginRequiredMixin, View):
    '''
    This view is responsible for edit any post. Or
    Swtich back any post to draft.
    '''

    template_name = 'write_blog/writePost.html'
    form_class = postForm(Post)

    def get_object(self, obj):
        return get_object_or_404(obj, postId=self.kwargs['id'])

    def get(self, request, slug, id):
        '''
        GET request to display the post edit form with
        initial values.
        '''

        post = self.get_object(Post)
        initial = {'category': post.category, }
        form = self.form_class(initial=initial, instance=post)

        return render(request, self.template_name, {'form': form})

    def post(self, request, slug, id):
        '''
        POST request to edit post or switch back any post
        to draft.
        '''
        post = self.get_object(Post)
        form = None

        if 'update' in request.POST:

            '''
            Edit post
            '''
            form = self.form_class(request.POST or None,
                                   request.FILES, instance=post)
            if form.is_valid():
                postSavingFormHandle(self.request, form)

                return urlRedirect(request.user, 'posts')

        else:

            '''
            Switch back post to draft and remove the post
            from publish post.
            '''
            self.form_class = postForm(Draft)
            form = self.form_class(request.POST or None, request.FILES)

            if form.is_valid():
                postSavingFormHandle(self.request, form, post)
                post.delete()

                return urlRedirect(request.user, 'drafts')

        return render(request, self.template_name, {'form': form})


class EditOrPublishDraft(LoginRequiredMixin, View):
    '''
    This View is responsible for Edit draft post. Or
    Final publishing the post
    '''

    form_class = postForm(Draft)
    template_name = 'write_blog/writePost.html'

    def get_object(self):
        _id = self.kwargs['id']
        return Draft.objects.get(postId=_id)

    def get(self, request, id):
        '''
        GET request to display the draft edit form with
        initial values.
        '''

        draft = self.get_object()
        initial = {'category': draft.category, }
        form = self.form_class(initial=initial, instance=draft)

        return render(request, self.template_name, {'form': form, 'editDraft': True})

    def post(self, request, id, *args, **kwargs):
        '''
        POST request to edit drafts or finally publish as post.
        '''
        draft = self.get_object()
        form = None

        if 'update-draft' in self.request.POST:

            '''
            If user edit any draft.
            '''
            form = self.form_class(
                self.request.POST or None, request.FILES, instance=draft)

            if form.is_valid():
                postSavingFormHandle(self.request, form)
                return urlRedirect(request.user, 'drafts')
        else:

            '''
            Finally publish draft as post.
            '''
            self.form_class = postForm(Post)
            form = self.form_class(
                self.request.POST or None, request.FILES)

            if form.is_valid():
                postSavingFormHandle(self.request, form, draft)
                draft.delete()

                return urlRedirect(request.user, 'posts')

        return render(request, self.template_name, {'form': form})


def postSavingFormHandle(request, form, obj=None):
    '''
    Helper function to handle the postCreatingOrSaving form.
    # parameters
    request: http resuest object.
    form: valid form instanace.
    '''
    post = form.save(commit=False)
    author = request.user
    post.author = f"{author.first_name} {author.last_name}"
    post.authorId = f"{author.userId}"

    if 'create' in request.POST or 'switch-draft' in request.POST:
        if post.featured_image == None and obj:
            post.featured_image = obj.featured_image

    if 'create' in request.POST:
        createPostMeta(post)
        post.publish()

    if 'update' in request.POST:
        createPostMeta(post)
        post.update()

    if 'save' in request.POST or 'switch-draft' in request.POST:
        post.create()

    post.save()

    '''
    Saving tags
    '''
    if 'create' in request.POST and post.tags:
        tagsList = post.tags.split(',')
        for tag in tagsList:
            obj, create = Tag.objects.get_or_create(
                name=tag.strip().lower()
            )
            obj.posts.add(post)

    return True


def urlRedirect(user, name='profile'):
    '''
    Helper function to handle url redirection.
    # parameters
    user: current user.
    name: url name from urls.py.
    '''
    return HttpResponseRedirect(reverse(f'dashboard:{name}', kwargs={
        'user': user.username,
        'id': user.userId
    }))


def slugify(text):
    '''
    Change any text into a valid slug
    '''
    text = unidecode.unidecode(text).lower()
    slug = re.sub(r'[\W_]+', '-', text)
    if slug[:1] == '-' and slug[-1:] == '-':
        slug = slug[1:-1]
    elif slug[:1] == '-':
        slug = slug[1:]
    elif slug[-1:] == '-':
        slug = slug[:-1]

    return slug


def html2Text(html):
    '''
    Convert html to text
    '''
    soup = BeautifulSoup(html, features="html.parser")
    return soup.get_text('\n')


def createPostMeta(post):
    '''
    Create post meta data if blank value provided
    '''
    if post.slug == None:
        slug = slugify(post.title)
        post.slug = slug[:75]

    if post.meta_title == None:
        post.meta_title = post.title[:60]

    if post.meta_description == None:
        text = html2Text(post.body)
        post.meta_description = text[:160].strip()

templates/write_blog/writePost.html
{% extends 'user_profile/dashboard.html' %}
{% load static %}

{% block dashboard_right_block_head %}
<title>Editor</title>
<link rel="stylesheet" href="{% static 'css/editor.css' %}">
<script defer src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
{% endblock %}

{% block dashboard_right_block %}
{% if user.isAuthor is False %}
<div class="">
    <p style="font-family: Josefin Sans, sans-serif; font-size: 1.2rem;">Please complete your profile before write any
        post</p>
    <a class="default-link" href="{% url 'dashboard:editProfile' user=user.username id=user.userId %}">Edit</a>
</div>
{% else %}
<form method="POST" class="editor" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {% if writePost%}
    <h1 class="editor__label">Add New Post</h1>
    {% else %}
    <h1 class="editor__label">Edit Post</h1>
    {% endif %}

    <div class="editor__fields">
        <div class="editor__fields__input title">
            {{form.title}}
            {% if form.errors %}
            {{form.errors.title}}
            {% endif %}
        </div>
        <div class="editor__fields__input--textarea body">
            {{form.body}}
            {% if form.errors %}
            {{form.errors.body}}
            {% endif %}
        </div>
        <div class="editor__fields__input tags">
            {{form.tags}}
            {% if form.errors %}
            {{form.errors.tags}}
            {% endif %}
        </div>
        <div class="editor__fields__input--select category">
            {{form.category}}
            {% if form.errors %}
            {{form.errors.category}}
            {% endif %}
        </div>
        <div class="editor__fields__input--image">
            <p class="editor__fields__input--label">Featured Image</p>
            {{form.featured_image}}
            {% if form.errors %}
            {{form.errors.featured_image}}
            {% endif %}
        </div>
        <div class="editor__meta-fields">
            <h2 class="editor__label">Post Meta Data <span>(Optional)</span> </h2>
            <div class="editor__fields__input--meta-title">
                <p class="editor__fields__input--label">Title <span class="message-info">(Max 60 characters
                        allowed)</span></p>
                {{form.meta_title}}
                {% if form.errors %}
                {{form.error}}
                {% endif %}
            </div>
            <div class="editor__fields__input--slug">
                <p class="editor__fields__input--label">Permalink <span class="message-info">(Max 75 characters
                        allowed)</span></p>
                {{form.slug}}
                {% if form.errors %}
                {{form.errors.slug}}
                {% endif %}
            </div>
            <div class="editor__fields__input--meta-desription">
                <p class="editor__fields__input--label">Description <span class="message-info">(Max 160
                        characters
                        allowed)</span></p>
                {{form.meta_description}}
                {% if form.errors %}
                {{form.errors.meta_description}}
                {% endif %}
            </div>
        </div>
    </div>
    {% if writePost %}
    <!-- Write post -->
    <div class="editor__btn">
        <button type="submit" class="btn editor__btn--publish" name="create" value="create">Publish</button>
        <button type="submit" class="btn editor__btn--draft" name="save" value="save">Save Draft</button>
    </div>
    {% elif editDraft %}
    <!-- Draft update or publish -->
    <div class="editor__btn">
        <button type="submit" class="btn editor__btn--publish" name="create" value="create">Publish</button>
        <button type="submit" class="btn editor__btn--draft" name="update-draft" value="update-draft">Update
            Draft</button>
    </div>
    {% else %}
    <!-- Post update -->
    <div class="editor__btn">
        <button type="submit" class="btn editor__btn--publish" name="update" value="update">Update</button>
        <button type="submit" class="btn editor__btn--publish" name="switch-draft" value="switch-draft">Switch
            Draft</button>
    </div>
    {% endif %}
</form>
{% endif %}
{% endblock %}