blog/urls.py
from django.urls import path, include

from .views import (
    Home,
    CategoryPost,
    PostPageView,
    ContactFormView,
    EmailSubscription,
    AboutView,
    PrivacyPolicyView,
    TermsOfServiceView,
    Search,
)
from blog.models import Post, Categorie, Comment
from write_blog.views import EditOrPublishDraft, EditOrSwitchPostToDraft

from compression_middleware.decorators import compress_page

app_name = 'blog'

urlpatterns = [
    path('', compress_page(Home.as_view()), name='home'),
    path('search', compress_page(Search.as_view()), name='search'),
    path('category/<slug:slug>',
         compress_page(CategoryPost.as_view()), name='category'),
    path('post/<str:id>/<slug:slug>/edit-post',
         compress_page(EditOrSwitchPostToDraft.as_view()), name='edit-post'),
    path('draft/<str:id>/edit-draft',
         compress_page(EditOrPublishDraft.as_view()), name='edit-or-publish-draft'),
    path('report/', compress_page(ContactFormView.as_view()), name='report'),
    path('contact/', compress_page(ContactFormView.as_view()), name='contact'),
    path('subscribe/', compress_page(EmailSubscription.as_view()), name='subscribe'),
    path('about/', compress_page(AboutView.as_view()), name='about'),
    path('privacy-policy/', compress_page(PrivacyPolicyView.as_view()),
         name='privacy_policy'),
    path('terms-of-service/',
         compress_page(TermsOfServiceView.as_view()), name='terms'),
    path('<slug:slug>', compress_page(
        PostPageView.as_view()), name='post_detail'),
]

codestim/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from blog.views import AboutView, handler404, handler500
from write_blog.views import image_upload

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('registration.urls')),
    path('profile/', include('user_profile.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('accounts/', include('allauth.urls')),
    path('media/images/uploads/', csrf_exempt(image_upload)),
    path('', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = handler404
handler500 = handler500

registration/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetConfirmView

from .views import User_signup, User_login, User_logout
from .forms import ResetPasswordForm

from compression_middleware.decorators import compress_page

app_name = 'registration'

urlpatterns = [
    path('signup/', compress_page(User_signup.as_view()), name='sign_up'),
    path('login/', compress_page(User_login.as_view()), name='log_in'),
    path('logout/', compress_page(User_logout), name='log_out'),
    path('password-reset/', compress_page(auth_views.PasswordResetView.as_view(template_name='authentication/resetPasswordFlow.html', success_url=reverse_lazy('registration:password_reset_done'))),
         name='password_reset'),

    path('password-reset/sent/', compress_page(auth_views.PasswordResetDoneView.as_view(template_name='authentication/resetPasswordFlow.html')),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', compress_page(PasswordResetConfirmView.as_view(
        template_name='authentication/resetPasswordForm.html',
        success_url=reverse_lazy('registration:password_reset_complete'),
        form_class=ResetPasswordForm
    )), name='password_reset_confirm'),

    path('password-reset/success/', compress_page(auth_views.PasswordResetCompleteView.as_view(
         template_name='authentication/resetPasswordFlow.html'
         )), name='password_reset_complete')
]

user_profile/urls.py
from django.urls import path, include

from .views import (
    Dashboard,
    Posts,
    Drafts,
    Comments,
    EditProfile,
    ProfileInfo,
    Search
)

from compression_middleware.decorators import compress_page

app_name = 'dashboard'

urlpatterns = [
    path('<str:user>/<str:id>/',
         compress_page(ProfileInfo.as_view()), name='profileInfo'),
    path('<str:user>/<str:id>/posts',
         compress_page(Posts.as_view()), name='posts'),
    path('<str:user>/<str:id>/drafts',
         compress_page(Drafts.as_view()), name='drafts'),
    path('<str:user>/<str:id>/comments',
         compress_page(Comments.as_view()), name='comments'),
    path('<str:user>/<str:id>/edit-profile',
         compress_page(EditProfile.as_view()), name='editProfile'),
    path('<str:user>/<str:id>/search',
         compress_page(Search.as_view()), name='search'),
    path('<str:user>/<str:id>/', include('write_blog.urls'))
]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
<title>About Us</title>
{% endblock %}

{% block body_block %}
<p>About</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head_block %}
    {% endblock %}
    <link rel="shortcut icon" href="/media/images/fevicon.png" type="image/x-icon">
    <link rel="preload" as="style" href="{% static 'css/base.css' %}" onload="this.rel='stylesheet'">
    <link rel="preload" as="style" href="{% static 'css/global.css' %}" onload="this.rel='stylesheet'">
    <link rel="preload" as='font' type="font" crossorigin
        href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;500;600;700&display=swap">
    <link rel="preload" as='font' type="font" crossorigin
        href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600&display=swap">
    <link rel="preload" as='font' type="font" crossorigin
        href="https://fonts.googleapis.com/css2?family=Catamaran:wght@300;400;500;600;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dosis:wght@400;500;600;700&display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600&display=swap">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Catamaran:wght@300;400;500;600;700&display=swap">
</head>

<body>
    <header id="header">
        {% include 'navbar.html' %}
    </header>

    <main id="main">
        <section class='main-content container'>
            {% block alert_block %}
            {% endblock %}

            {% block body_block %}
            {% endblock %}
        </section>
    </main>

    <footer id="footer" class="footer">
        {% include 'footer.html' %}
    </footer>
    {% block internal_style %}
    {% endblock %}
    {% block script_block %}
    {% endblock %}
    <script async defer src="{% static 'js/blog.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'css/contactForm.css' %}">
<script defer src="{% static 'js/closeAlert.js' %}"></script>
{% if request.path == '/contact/' %}
<title>Contact Us</title>
{% else %}
<title>Report</title>
{% endif %}
{% endblock %}

{% block alert_block %}
{% include 'message.html' with message=message %}
{% endblock %}

{% block body_block %}
<div class="formwrapper">
    <form method="POST" class="form">
        {% if request.path == '/contact/' %}
            <h1 class="form__name">Contact Us</h1>
        {% else %}
            <h1 class="form__name">Report an issue</h1>
        {% endif %}
        {% csrf_token %}
            {% for field in form %}
                <div class='form__fieldwrapper flex flex-column'>
                    <label class="form__fieldwrapper--label" for="{{field.id_for_label}}">{{field.label}}</label>
                    {{field}}
                    {{field.errors}}
                </div>
            {% endfor %}
        <button class="form__btn btn" type="submit" name="send">Submit</button>
    </form>
</div>

{% endblock %}

templates/error.html
{% extends 'base.html' %}
{% load static %}
{% block head_block %}
<title>{{error_code}} error</title>
<style>
    * {
        padding: 0;
        margin: 0;
        font-family: "Nunito Sans", sans-serif;
    }

    .error-wrapper {
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    .error-code {
        font-size: 6rem;
        font-weight: 700;
        color: #31708f;
    }

    .error-text {
        font-size: 2rem;
        color: #41444b;
        font-weight: 700;
        margin-bottom: 1rem;
    }

    .error-return-btn {
        text-decoration: none;
        padding: .5rem 1rem;
        background-color: #851de0;
        color: #ebecf1;
        border-radius: .3rem;
    }
</style>
{% endblock %}
{% block body_block %}
{{error_code}}
<div class="error-wrapper">
    <h1 class="error-code">{{error_code}}</h1>
    <h1 class="error-text">{{error_text}}</h1>
    <a class="error-return-btn" href="{% url 'blog:home' %}">Home</a>
</div>
{% endblock %}

templates/footer.html
<div class="footer__content container">
    <section class="footer__items--cta section cta">
        <div class="section__cta">
            <h3 class="section--title">Subscribe our newsletter for the latest update</h3>
            <div class="section--body--cta">
                <form class="section--email-input flex" action="{% url 'blog:subscribe' %}?next={{request.path}}"
                    method="POST">
                    {% csrf_token %}
                    {% for field in email_subscribe_form %}
                    {{field}}
                    {{field.errors}}
                    {% endfor %}
                    <button class="btn sub-btn" type="submit">Subscribe</button>
                </form>
            </div>
        </div>
    </section>
    <section class="footer__items--links section links">
        <div class="section__links ">
            <div class="section--body">
                <ul class="section--link-list flex">
                    <li class="list"><a class="default-link page-link" href="{% url 'blog:about' %}">About Us</a></li>
                    <li class="list"><a class="default-link page-link" href="{% url 'blog:contact' %}">Contact Us</a>
                    </li>
                    <li class="list"><a class="default-link page-link" href="{% url 'blog:privacy_policy' %}">Privacy
                            Policy</a></li>
                    <li class="list"><a class="default-link page-link" href="{% url 'blog:terms' %}">Terms of
                            Service</a></li>
                    <li class="list"><a class="default-link page-link" href="{% url 'blog:report' %}">Report An
                            Issue</a></li>
                </ul>
            </div>
        </div>
    </section>
</div>
<section class="footer__bar bar">
    <div class="footer__bar--text container">
        Copyright &#169 2020 <a class="default-link" href="{% url 'blog:home' %}">Codestim.com</a> All right reserved
    </div>
</section>

templates/message.html
{% load static %}
{% if messages %}
<div id="alert-box">
    <script defer src="{% static 'js/closeAlert.js' %}"></script>
    {% for message in messages %}
    <div class="notification-container {{message.tags}}" role="alert">
        <div class="flex center-align" style="justify-content: space-between;">
            <span>{{message}}</span>
            <svg id='close-alert-icon' class="close-alert-icon" xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 352 512">
                <path
                    d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z" />
            </svg>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/modalForm.html
<form method="POST" action="" class="modal">
    {% csrf_token %}
    <div class="modal__header flex center-align">
        <svg class="fas fa-trash-alt modal__header--delete-icon" xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 448 512">
            <path
                d="M32 464a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128H32zm272-256a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zm-96 0a16 16 0 0 1 32 0v224a16 16 0 0 1-32 0zM432 32H312l-9.4-18.7A24 24 0 0 0 281.1 0H166.8a23.72 23.72 0 0 0-21.4 13.3L136 32H16A16 16 0 0 0 0 48v32a16 16 0 0 0 16 16h416a16 16 0 0 0 16-16V48a16 16 0 0 0-16-16z" />
        </svg>
        {% if type == "post" %}
        <h3 class="modal__header--text">Delete this post</h3>
        {% elif type == "draft" %}
        <h3 class="modal__header--text">Discard this draft</h3>
        {% endif %}
        <svg class="fas fa-times modal__header--close-icon close" xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 352 512">
            <path
                d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z" />
        </svg>
    </div>
    <p class="modal__body">Are you sure you want to delete the {{type}} with Title: <br> <span
            id="spanPostTitle"></span>
    </p>
    <div class="modal__btn">
        <button class="btn modal__btn--confirm" id="confirm-delete" type="submit" name="id"
            value={{post.postId}}>Delete</button>
    </div>
</form>

templates/navbar.html
{% load static %}
<nav class='nav-bar flex flex-row center-align container'>
	<svg class="nav-bar--burger" id="burger" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
		<path
			d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" />
	</svg>
	<svg style="display: none;" class="nav-bar--cross" id="cross" xmlns="http://www.w3.org/2000/svg"
		viewBox="0 0 352 512">
		<path
			d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z" />
	</svg>
	<a href="{% url 'blog:home' %}" class="nav-bar--logo-link">
		<img src="{% static 'media/logo.svg' %}" alt="codestim" id="logo">
	</a>
	<ul class="nav-bar__menu" id='navigation-menu'>
		<li class="list"><a class='nav-bar__menu__item link' href="/category/Javascript">Javascript</a></li>
		<li class="list"><a class='nav-bar__menu__item link' href="/category/Python">Python</a>
		</li>
		<li class="list"><a class='nav-bar__menu__item link' href="/category/Web-development">Web</a></li>
		<li class="list"><a class='nav-bar__menu__item link' href="/category/Programming">Programming</a>
		</li>

		<form action="{% url 'blog:search' %}" class="nav-bar__menu--search-bar flex flex-row" method="GET">
			<input class="search-bar--input" required type="search" name="query" placeholder="Search posts..."
				id="search">
			<button class="search-bar__btn" title="search" aria-label="search" type="submit">
				<svg class="search-bar__btn--icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
					<path
						d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z" />
				</svg>
			</button>
		</form>
	</ul>
	<div class="nav-bar__auth">
		<div class="auth flex flex-row center-align">
			{% if user.is_authenticated %}
			<div id='profileButton' class="auth__profile flex flex-row center-align link">
				<svg class="auth__profile--icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512">
					<path
						d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z" />
				</svg>
				<span class="auth__profile--username">{{user}}</span>
			</div>
			<div class='auth__options'>
				<ul class="auth__options__list">
					<li class="auth__options__list--item list">
						<a class="default-link" href="{% url 'dashboard:profileInfo' user=user id=user.userId %}">
							Profile</a>
					</li>
					<li class="auth__options__list--item list">
						<a class="default-link" href="{% url 'dashboard:posts' user=user id=user.userId %}">
							Posts
						</a>
					</li>
					<li class="auth__options__list--item list">
						<a class="default-link" href="{% url 'dashboard:drafts' user=user id=user.userId %}">
							Drafts
						</a>
					</li>
					<li class="auth__options__list--item list"><a class="default-link"
							href="{% url 'dashboard:comments' user=user id=user.userId %}">Comments</a></li>
					<li class="auth__options__list--item list"><a class="default-link"
							href="{% url 'dashboard:write_blog:write_post' user=user id=user.userId %}">Write Post</a>
					</li>
					<li class="auth__options__list--item list"><a class="default-link"
							href="{% url 'registration:log_out' %}">Log Out</a></li>

				</ul>
			</div>
			{% else %}
			<div class="flex flex-row">
				<!-- <a class="auth__btn link btn" href="{% url 'registration:sign_up' %}">Write</a> -->
				<a class="auth__btn link btn" href="{% url 'registration:log_in' %}">Write Post</a>
			</div>
			{% endif %}
		</div>
	</div>

</nav>

templates/privacyPolicy.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
<title>Privacy Policy</title>
{% endblock %}

{% block body_block %}
<p>Privacy Policy</p>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
<title>Search result</title>
<link rel="stylesheet" href="{% static 'css/searchResult.css' %}">
{% endblock %}

{% block body_block %}
<div class="search-result">
    <h1 class="page-title">{{posts|length}} matching search result{{posts|pluralize}} found</h1>
    {% if posts %}
    <div class="post-list">
        {% for post in posts %}
        <div class="post-wrapper">
            <div class="post__thumbnail">
                {% if post.featured_image %}
                <img class="post__thumbnail--image" src="{{ post.featured_image.url }}" alt="image">
                {% else %}
                <img class="post__thumbnail--image" src="{% static 'media/no_image.png' %}" alt="">
                {% endif %}
            </div>
            <div class="post__details">
                <h3 style="line-height: 1.2rem;">
                    <a class="post--title link" href="{% url 'blog:post_detail' slug=post.slug %}">{{post.title}}</a>
                </h3>
                <p class="post--meta">{{post.publish_date}} | {{post.category}}</p>
                <article class="post--content">
                    {{post.body|safe|truncatewords_html:20}}
                </article>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
            </span>

            {% if posts.has_next %}
            <a href="?page={{ posts.next_page_number }}">next</a>
            <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    {% else %}
    <div class="no-result-wrapper">
        <p class="no-result--text">Sorry, we couldn't find any content for "<span
                class="no-result--query">{{query}}</span>".
            <br>
            Please try with different keyword.
        </p>
        <form action="{% url 'blog:search' %}" class="search-bar flex flex-column" method="GET">
            <input class="search-bar--input" required type="search" name="query" placeholder="Search posts" id="search">
            <button class="btn search-bar--btn  " type="submit">Search</button>
        </form>
    </div>

    {% endif %}
</div>
{% endblock %}

templates/termsOfService.html
{% extends 'base.html' %}
{% load static %}

{% block head_block %}
<title>Terms of service</title>
{% endblock %}

{% block body_block %}
<p>Terms of service</p>
{% endblock %}